### PR TITLE
fix: Fix compilation error for Spark 3.2 & 3.3

### LINKED ISSUE #113: Build with Spark 3.2 failed
### Describe the bug

comet fails to compile with Spark version 3.2

```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check (default) on project comet-parent-spark3.2_2.12: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check failed: Unable to load the mojo 'check' in the plugin 'com.diffplug.spotless:spotless-maven-plugin:2.43.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/diffplug/spotless/maven/SpotlessCheckMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

```
[ERROR] spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:1069: value offset is not a member of org.apache.spark.sql.DataFrame
```

### Steps to reproduce

```
PROFILES="-Pspark-3.2" make
```

### Expected behavior

Compilation passes

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sunchao**
## Which issue does this PR close?

Closes #113.

## Rationale for this change

Comet currently doesn't compile with Spark 3.2 and 3.3 since it uses `Dataset.offset` API, was introduced in https://issues.apache.org/jira/browse/SPARK-39159 which is Spark 3.4. 

## What changes are included in this PR?

This replaces the API usage with a SQL text `OFFSET`, and also mark the test as Spark 3.4+ only.

## How are these changes tested?

Manually tested locally with `PROFILES="-Pspark-3.2" make`

### CODE REVIEW

**Review by viirya — APPROVED** [review]

**Comment by sunchao** [comment]
Thanks, merged
