### PR TITLE
build: Upgrade spotless version to 2.43.0

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #.

## Rationale for this change

Current spotless `2.29.0` doesn't work with Apache Maven 3.9.6 + Java version: 21.0.2.
    
```
java.lang.reflect.InvocationTargetException
   at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:118)
  at java.lang.reflect.Method.invoke (Method.java:580)
...
Caused by: java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
...
```

### CODE REVIEW

File: .github/actions/java-test/action.yaml [hunk 1]
```diff
@@ -38,9 +38,17 @@ runs:
       shell: bash
       run: |
         echo "JAVA_VERSION=${JAVA_VERSION}"
-        ./mvnw -B compile test-compile scalafix:scalafix -Psemanticdb -Djava.version=${JAVA_VERSION}
+        if [ $JAVA_VERSION == "1.8" ]; then
+          ./mvnw -B compile test-compile scalafix:scalafix -Psemanticdb -Djava.version=${JAVA_VERSION} -Dspotless.version=2.29.0
```
Comment (sunchao) [inline .github/actions/java-test/action.yaml:42]: is it OK to use 2.29.0 for Java 8?

Comment (viirya) [reply .github/actions/java-test/action.yaml:42]: This line uses 2.29.0 for Java 8, isn't?

Comment (sunchao) [reply .github/actions/java-test/action.yaml:42]: I mean whether we'll run into the issue mentioned in the PR description if we use 2.29 for Java 8

Comment (sunchao) [reply .github/actions/java-test/action.yaml:42]: oh cool.

**Review by sunchao — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks.
